export const PRODUCTS_SEED = [
  {
    slug: 'macbook-pro-14-m3-pro',
    name: 'MacBook Pro 14"',
    tagline: 'Supercharged by M3 Pro.',
    description: 'MacBook Pro with M3 Pro chip delivers breakthrough performance for demanding workflows. With up to 18 hours of battery life and an incredible Liquid Retina XDR display, it redefines what a pro laptop can do.',
    price: 199900,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&q=80',
    ],
    category: 'mac',
    featured: true,
    specs: {
      'Chip': 'Apple M3 Pro',
      'CPU': '11-core CPU',
      'GPU': '14-core GPU',
      'Memory': '18GB unified memory',
      'Storage': '512GB SSD',
      'Display': '14.2-inch Liquid Retina XDR',
      'Battery': 'Up to 18 hours',
      'Weight': '3.5 pounds',
    },
    stock: 30,
  },
  {
    slug: 'macbook-air-13-m2',
    name: 'MacBook Air 13"',
    tagline: 'Strikingly thin. Surprisingly powerful.',
    description: 'The redesigned MacBook Air with M2 is incredibly thin and delivers remarkable performance. With up to 18 hours of battery life and a fanless design, it\'s the world\'s best consumer laptop.',
    price: 109900,
    images: [
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&q=80',
    ],
    category: 'mac',
    featured: false,
    specs: {
      'Chip': 'Apple M2',
      'CPU': '8-core CPU',
      'GPU': '8-core GPU',
      'Memory': '8GB unified memory',
      'Storage': '256GB SSD',
      'Display': '13.6-inch Liquid Retina',
      'Battery': 'Up to 18 hours',
      'Weight': '2.7 pounds',
    },
    stock: 45,
  },
  {
    slug: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    tagline: 'Titanium. So strong. So light. So Pro.',
    description: 'iPhone 15 Pro features a strong and light titanium design, an advanced camera system with 5x optical zoom, Action Button, and the A17 Pro chip — the most powerful chip ever in a smartphone.',
    price: 99900,
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484429be?w=800&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&q=80',
    ],
    category: 'iphone',
    featured: true,
    specs: {
      'Chip': 'A17 Pro',
      'Display': '6.1-inch Super Retina XDR',
      'Camera': '48MP Main | 12MP Ultra Wide | 12MP 5x Telephoto',
      'Storage': '128GB',
      'Battery': 'Up to 23 hours video playback',
      'Material': 'Titanium',
      'Water Resistance': 'IP68',
    },
    stock: 60,
  },
  {
    slug: 'iphone-15',
    name: 'iPhone 15',
    tagline: 'A total powerhouse.',
    description: 'iPhone 15 features the Dynamic Island, a 48MP camera that captures stunning detail, and the A16 Bionic chip. With USB-C connectivity and up to 26 hours of battery life, it does it all.',
    price: 79900,
    images: [
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80',
    ],
    category: 'iphone',
    featured: false,
    specs: {
      'Chip': 'A16 Bionic',
      'Display': '6.1-inch Super Retina XDR',
      'Camera': '48MP Main | 12MP Ultra Wide',
      'Storage': '128GB',
      'Battery': 'Up to 26 hours video playback',
      'Connector': 'USB-C',
    },
    stock: 80,
  },
  {
    slug: 'ipad-pro-12-m2',
    name: 'iPad Pro 12.9"',
    tagline: 'Impossibly thin. Incredibly powerful.',
    description: 'iPad Pro with the M2 chip is the ultimate iPad. Featuring a stunning 12.9-inch Liquid Retina XDR display, Apple Pencil hover, and blazing fast connectivity with Wi-Fi 6E and 5G.',
    price: 109900,
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    ],
    category: 'ipad',
    featured: false,
    specs: {
      'Chip': 'Apple M2',
      'Display': '12.9-inch Liquid Retina XDR',
      'Storage': '128GB',
      'Connectivity': 'Wi-Fi 6E',
      'Camera': '12MP Wide | 10MP Ultra Wide',
      'Face ID': 'Yes',
    },
    stock: 25,
  },
  {
    slug: 'airpods-pro-2nd-gen',
    name: 'AirPods Pro',
    tagline: 'Adaptive Audio. Now playing.',
    description: 'AirPods Pro feature Adaptive Audio — a new mode that seamlessly blends Active Noise Cancellation and Transparency mode. With the H2 chip, you get personalized Spatial Audio and 2x more ANC than the previous generation.',
    price: 24900,
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80',
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80',
    ],
    category: 'airpods',
    featured: true,
    specs: {
      'Chip': 'Apple H2',
      'Noise Cancellation': 'Active Noise Cancellation',
      'Battery': 'Up to 6 hours (30 hours with case)',
      'Water Resistance': 'IPX4',
      'Audio': 'Personalized Spatial Audio',
      'Connectivity': 'Bluetooth 5.3',
    },
    stock: 100,
  },
  {
    slug: 'airpods-3rd-gen',
    name: 'AirPods (3rd generation)',
    tagline: 'Contoured comfort. Dynamic sound.',
    description: 'AirPods (3rd generation) feature Spatial Audio with dynamic head tracking, Adaptive EQ, and a new contoured design. With MagSafe Charging Case and up to 30 hours total listening time.',
    price: 16900,
    images: [
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80',
    ],
    category: 'airpods',
    featured: false,
    specs: {
      'Chip': 'Apple H1',
      'Battery': 'Up to 6 hours (30 hours with case)',
      'Water Resistance': 'IPX4',
      'Audio': 'Spatial Audio',
      'Charging': 'MagSafe / Lightning',
    },
    stock: 90,
  },
  {
    slug: 'apple-watch-series-9',
    name: 'Apple Watch Series 9',
    tagline: 'Smarter. Brighter. Mightier.',
    description: 'Apple Watch Series 9 features the new S9 chip for on-device Siri with health data access, a brighter always-on display, Double Tap gesture, and the ability to measure your blood oxygen levels.',
    price: 39900,
    images: [
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&q=80',
    ],
    category: 'watch',
    featured: false,
    specs: {
      'Chip': 'Apple S9',
      'Display': 'Always-On Retina LTPO OLED',
      'Health': 'Blood Oxygen | ECG | Heart Rate',
      'Water Resistance': '50 meters',
      'Battery': 'Up to 18 hours',
      'Connectivity': 'GPS + Cellular',
    },
    stock: 40,
  },
  {
    slug: 'magsafe-charger',
    name: 'MagSafe Charger',
    tagline: 'Perfectly aligned. Instantly charged.',
    description: 'The MagSafe Charger connects magnetically to iPhone 12 or later for faster wireless charging up to 15W. The flexible cable makes it easy to charge in any position.',
    price: 3900,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
    ],
    category: 'accessories',
    featured: false,
    specs: {
      'Compatibility': 'iPhone 12 and later',
      'Power': 'Up to 15W',
      'Cable Length': '1m',
      'Connector': 'USB-C',
    },
    stock: 200,
  },
  {
    slug: 'apple-pencil-2nd-gen',
    name: 'Apple Pencil (2nd generation)',
    tagline: 'The most capable Apple Pencil yet.',
    description: 'Apple Pencil (2nd generation) attaches magnetically and wirelessly charges on iPad Pro and iPad Air. With pixel-perfect precision and low latency, it\'s perfect for drawing, sketching, and note‑taking.',
    price: 12900,
    images: [
      'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&q=80',
    ],
    category: 'accessories',
    featured: false,
    specs: {
      'Compatibility': 'iPad Pro (3rd gen+), iPad Air (4th gen+)',
      'Charging': 'Wireless via MagSafe',
      'Latency': '9ms',
      'Tilt Sensitivity': 'Yes',
      'Double Tap': 'Switch tools',
    },
    stock: 70,
  },
];
